In [1]:
import numpy as np
import nashpy as nash

https://towardsdatascience.com/game-theory-in-python-with-nashpy-cb5dceab262c
https://www.youtube.com/watch?v=dorUO5Z
PFtE&ab_channel=GameTheoryOnline

In [2]:
A = np.array([[2,0],[4,2]]) # A is the row player
B = np.array([[4,2],[2,0]]) # B is the column player
game1 = nash.Game(A,B)
print(game1)
equilibria = game1.support_enumeration()
for eq in equilibria:
    print(eq)

Bi matrix game with payoff matrices:

Row player:
[[2 0]
 [4 2]]

Column player:
[[4 2]
 [2 0]]
(array([0., 1.]), array([1., 0.]))


In [3]:
A = np.array([[4,0],[0,2]]) # A is the row player
B = np.array([[2,0],[0,4]]) # B is the column player
game2 = nash.Game(A,B)
print(game2)
equilibria = game2.support_enumeration()
for eq in equilibria:
    print(eq)


Bi matrix game with payoff matrices:

Row player:
[[4 0]
 [0 2]]

Column player:
[[2 0]
 [0 4]]
(array([1., 0.]), array([1., 0.]))
(array([0., 1.]), array([0., 1.]))
(array([0.66666667, 0.33333333]), array([0.33333333, 0.66666667]))


In [4]:
sigma_r = np.array([.67,.33])
sigma_c = np.array([.33,.67])
pd = nash.Game(A, B)
pd[sigma_r, sigma_c]

array([1.3266, 1.3266])